server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/eventpulse}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
      specific.avro.reader: true
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
      sasl.client.callback.handler.class: ${KAFKA_SASL_CLIENT_CALLBACK_HANDLER_CLASS:}
    consumer:
      group-id: ${RAW_EVENTS_CONSUMER_GROUP:event-processor-v2}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true

app:
  kafka:
    topics:
      raw-events: ${RAW_EVENTS_TOPIC:raw-events}
      push-notifications: ${PUSH_NOTIFICATIONS_TOPIC:push-notifications}
      notification-status: ${NOTIFICATION_STATUS_TOPIC:notification-status}
